# Zentropy Development Infrastructure
# Provides PostgreSQL database and Redis cache for local development
services:
  postgres:
    # Primary data store for all application data
    image: postgres:15
    container_name: zentropy_db
    environment:
      POSTGRES_DB: zentropy
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    # Rate limiting and caching layer
    image: redis:7-alpine
    container_name: zentropy_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

volumes:
  postgres_data:
  redis_data: